about.url=https://github.com/BertrandDechoux/OrganicBuilder

level.first.action.smallicon	= /graphics/first.svg
level.previous.action.smallicon	= /graphics/previous.svg
level.next.action.smallicon		= /graphics/next.svg
level.last.action.smallicon		= /graphics/last.svg

simulation.run.action.smallicon		= /graphics/play.svg
simulation.stop.action.smallicon	= /graphics/pause.svg
simulation.reset.action.smallicon	=  /graphics/reset.svg

about.action.smallicon	= /graphics/help.svg